feat(taplo-lsp): import #:schema-directives relative to file
tamasfe/taplo pull request #119
Opened 2021-06-04 19:06 UTC by Profpatsch

Fixes #118, see commit message.

I also added a bunch of comments while figuring out the logic.

2021-06-04 19:08 UTC, Profpatsch commented
Another improvement that could be made for this schema code: If a schema directive is found, but doesn’t point to a valid schema file, return a lsp message marking the schema directive with the error.

2021-06-05 11:03 UTC, tamasfe requested changes

2021-06-05 11:09 UTC, tamasfe commented
Thank you, the schema handling logic will require some more thoughts and probably a smaller refactoring (showing errors in diagnostics, and including it in the `taplo-cli` as well), for now this should work just fine.

Other than one thing, this looks good to me.

2021-06-05 11:13 UTC, tamasfe commented on js/vscode/src/extension.ts
> -  output = vscode.window.createOutputChannel("Even Better TOML");
Ah, I missed the commit message. If this is removed, the global `output` variable should be removed as well not just its lazy initialization.

2021-06-07 08:55 UTC, Profpatsch commented on js/vscode/src/extension.ts
> -  output = vscode.window.createOutputChannel("Even Better TOML");
I didn’t see that it’s a global variable, I dropped the commit completely. Apparently it’s used in some other parts of the program.

2021-06-07 08:56 UTC, Profpatsch commented
Cool, I dropped the commit.

2021-06-07 11:19 UTC, merged