taplo-cli: add ENV variable support
tamasfe/taplo pull request #427
Opened 2023-07-01 02:18 UTC by razvanazamfirei

This pull request improves the configuration file lookup logic in taplo-cli. The changes enable the CLI to search for a configuration file in the `TAPLO_CONFIG` environment variable if no configuration file is found in the current working directory and no explicit path has been provided by the user.

Changes:

1. Added support for TAPLO_CONFIG in the `load_config` function.
2. Minor documentation updates

2023-07-01 08:18 UTC, ia0 reviewed
Thanks for the PR, that's a good idea!

2023-07-01 08:18 UTC, ia0 commented on crates/taplo-cli/src/args.rs
>      #[clap(long, short)]
`clap` already supports this feature. Let's remove the added documentation (it is added by clap), add the `env` feature to the `clap` dependency, and update the code to:

```suggestion
    #[clap(long, short, env = "TAPLO_CONFIG")]
```

2023-07-01 08:18 UTC, ia0 commented on crates/taplo-cli/src/lib.rs
> +                config_path = Some(path.into());
Let's revert everything in this file because it's supported by `clap`.

2023-07-01 08:18 UTC, ia0 commented on site/site/cli/usage/configuration.md
> +If a config file is not provided and no file is found in the current working directory, Taplo CLI will try to retrieve the configuration file path from the `TAPLO_CONFIG` environment variable.
Let's remove this and instead update the line above to say that it is also possible to set the `TAPLO_CONFIG` environment variable (the `--config` flag taking precedence).

2023-07-16 11:19 UTC, razvanazamfirei commented
Thanks, @ia0! Changes made.

2023-07-16 11:45 UTC, ia0 requested changes
Thanks!

You also need to add the `env` feature to `clap`.

```diff
-clap = { version = "3.0.0", features = ["derive", "cargo"] }
+clap = { version = "3.0.0", features = ["derive", "cargo", "env"] }
```

2023-07-16 11:45 UTC, ia0 commented on crates/taplo-cli/src/args.rs
> +    /// Configuration file can be specified in $TAPLO_CONFIG
There's no need for additional comment, `clap` already adds the following line:

```
    -c, --config <CONFIG>
            Path to the Taplo configuration file.
            
            [env: TAPLO_CONFIG=]
```

2023-07-16 13:10 UTC, ia0 approved these changes
Thanks!

2023-07-16 13:26 UTC, panekj approved these changes

2023-07-16 13:26 UTC, merged